[package]
name = "bevy_mod_desync"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.13.2"
bevy_ecs = "0.13.2"
crc = "3.2.1"
serde = "1.0.203"
serde_json = "1.0.117"

[dev-dependencies]
serde = { version = "1.0.203", features = ["derive"] }
